### ISSUE TITLE
#15 breaks itest (incorrect usage of safe_load)

### ISSUE THREAD

**Issue by asottile** [Yelp/service_configuration_lib#16]
```
All scripts are in the path...
Failed to parse YAML from /nail/etc/services/fake_runs_on_1/service.yaml
Traceback (most recent call last):
  File "/usr/bin/services_deployed_here", line 20, in <module>
    for service in sorted(service_configuration_lib.services_deployed_here()):
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 218, in services_deployed_here
    return set(list_extra_deployed_here() + services_deployed_on(hostname))
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 222, in services_deployed_on
    service_configuration = read_services_configuration()
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 151, in read_services_configuration
    service_info = read_service_configuration_from_dir(rootdir, service_dirname)
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 127, in read_service_configuration_from_dir
    service_information = read_service_information(service_file)
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 82, in read_service_information
    return _read_yaml_file(service_file)
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 90, in _read_yaml_file
    data = load_yaml(fd.read())
  File "/usr/lib/python2.7/dist-packages/service_configuration_lib/__init__.py", line 62, in load_yaml
    return yaml.safe_load(fd, Loader=yaml.CLoader)
TypeError: safe_load() got an unexpected keyword argument 'Loader'
Service fake_runs_on_1 ISN'T showing up in services_deployed_here but should be
make: *** [itest_xenial] Error 1
```

**Comment by asottile** [comment]
CC @solarkennedy
