### ISSUE TITLE
`make itest_lucid` fails

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/service_configuration_lib#6]
```
{:level=>:warn, :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :timestamp=>"2015-11-05T13:21:29.   %6N+0000"}
/usr/lib/ruby/1.8/find.rb:39:in `find': no block given (LocalJumpError)
        from /usr/lib/ruby/1.8/find.rb:38:in `catch'
        from /usr/lib/ruby/1.8/find.rb:38:in `find'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:671:in `add_path'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:692:in `write_conffiles'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:590:in `write_control_tarball'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:389:in `output'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:475:in `execute'
        from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
        from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /var/lib/gems/1.8/gems/fpm-1.4.0/bin/fpm:8
        from /usr/bin/fpm:23:in `load'
        from /usr/bin/fpm:23
make: *** [package_lucid] Error 1
```

Idk how long this has been happening for - Looking at the Jenkins builds, this was failing before we rewrote any history so I don't think it's been caused by that.

**Comment by Rob-Johnson** [comment]
fixed in #8
